boenergo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from .views import index, page1, page2

urlpatterns = [
    path('', index, name='index'),
    path('page1', page1, name='page1'),
    path('page2', page2, name='page2'),
]

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms


class CalcForm(forms.Form):
    a = forms.CharField(max_length=10)
    b = forms.CharField(max_length=10)
    c = forms.CharField(max_length=10)


class RandForm(forms.Form):
    num = forms.IntegerField(min_value=0, max_value=100)

main/views.py
from django.shortcuts import render
from .forms import CalcForm, RandForm
from .services import solve_equation, get_color


def index(request):
    return render(request, 'main/index.html')


def page1(request):

    if request.method == 'POST':
        form = CalcForm(request.POST)
        if form.is_valid():
            a = int(form.cleaned_data['a'])
            b = int(form.cleaned_data['b'])
            c = int(form.cleaned_data['c'])
            ans = solve_equation(a, b, c)
            return render(request, 'main/page1.html', {'form': form, 'ans': ans})
    else:
        form = CalcForm()
    return render(request, 'main/page1.html', {'form': form})


def page2(request):

    if request.method == 'POST':
        form = RandForm(request.POST)
        if form.is_valid():
            ans = get_color()
            return render(request, 'main/page2.html', {'form': form, 'ans': ans})
    else:
        form = RandForm()
    return render(request, 'main/page2.html', {'form': form})

main/templates/main/index.html
{% extends 'main/layot.html' %}

{% block title %}Главная страница{% endblock %}

{% block text %}
    <div class="features">
        <a href="page1"><button class="btn btn-warning">Онлайн калькулятор</button></a>
        <a href="page2"><button class="btn btn-warning">Угадать цвет</button></a>
    </div>
{% endblock %}

main/templates/main/layot.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
</head>
<body>
    <aside>
        <span class="logo">ZhMurzin</span>
        <h3>Навигация</h3>
        <ul>
            <a href="{% url 'index' %}"><li><i class="fas fa-home"></i>Главная</li></a>
            <a href="{% url 'page1' %}"><li><i class="fas fa-calculator"></i>Калькулятор</li></a>
            <a href="{% url 'page2' %}"><li><i class="fas fa-palette"></i>Угадать цвет</li></a>
        </ul>
    </aside>
    <main>
        {% block text %}
        {% endblock %}
    </main>
</body>
</html

main/templates/main/page1.html
{% extends 'main/layot.html' %}

{% block title %} Калькулятор {% endblock %}

{% block text %}
    <div class="features">
        <form action="page1" method="post">
            {% csrf_token %}
            <h2>Введите коэффициенты a, b, c</h2>
            <p></p>
            {{ form.a }}
            <label for="">x^2+</label>
            {{ form.b }}
            <label for="">x+</label>
            {{ form.c }}
            <label for="">=0</label>
            <p></p>
            <input type="submit" class="btn btn-warning" value="Решить">
            <style>
                #id_a, #id_b, #id_c {
                    width: 40px;
                }
            </style>
        </form>
        {% if ans is not empty %}
            <p>Ответ: {{ ans }}</p>
        {% endif %}

    </div>
{% endblock %}

main/templates/main/page2.html
{% extends 'main/layot.html' %}

{% block title %} Угадать цвет {% endblock %}

{% block text %}
    <div class="features">
        <form action="" method="post">
            {% csrf_token %}
            <h2>Введите номер предмета</h2>
            <p></p>
            {{ form.num }}
            <p></p>
            <input type="submit" class="btn btn-warning" value="ОК">
            <style>
                #id_a, #id_b, #id_c {
                    width: 40px;
                }
            </style>
        </form>
        {% if ans is not empty %}
            <p>{{ ans }}</p>
        {% endif %}
    </div>
{% endblock %}